var unitTest = [
	  "                                          ",
	  "                                          ",
	  "                                          ",
	  "                      xxxxxxx             ",
	  "                                          ",
	  "              xxxx                        ",
	  "                               xxxxx      ",
	  "                                          ",
	  "     =                 =xxx               ",
	  "                                          ",
	  "     x=    =      =   ! x                 ",
	  "                    x        2xxx         ",
	  "                                    o     ",
	  "                                    o     ",
	  "                                    oxx   ",
	  " 1       o   o    o                 ov|   ",
	  "xx        -x                            xx",
	  "!                   +                   v|",
	  "!  z   zp    p      x                     ",
	  "!  y   y#@         Bx                     ",
	  "!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	];
var easy = [
	  "                   x  ",
	  "             o        ",
	  "             o        ",
	  "      x=     o     o  ",
	  "             x     o  ",
	  "                   o  ",
	  "  x                x  ",
	  "  x         o o    x  ",
	  "  x        xxxxx   x  ",
	  "  x  1             x  ",
	  "  xxxxx!!!!!!!!!!!!x  ",
	  "  xxxxxxxxxxxxxxxxxx  ",
	  "                      "
	];
	
var simpleAbyss = [
	  "                    x xx x       xxxx ",
	  "                      xx v       v x  ",
	  "                      xx     x     x  ",
	  "                      xx v   x   v x  ",
	  "                      xx     x     x  ",
	  "                      xx     x     x  ",
	  "                      x      v        ",
	  "                    xxx               ",
	  "                   ox                 ",
	  "                   =x                 ",
	  "  x                xx        1        ",
	  "  x             o  x         x        ",
	  "  x   =         o  x                  ",
	  "  xxxxx         o  x     o       x    ",
	  "  xxxxx         x  x     o       x    ",
	  "  xxxxx  o      o  v     o   x   x    ",
	  "  xxxxx  x               o   x   x    ",
	  "  xxxxx                  o   x   x    ",
	  "  xxxxx       o          o   x   x    ",
	  "  xxxxx      xxxxx       o   x   x    ",
	  "  xxxxx                  o   x   x    ",
	  "  xxxxx!!!!!!!!!!!!!!!xxxx!!!x!!!x!!!!",
	];
	
var bombsGalore = [
	  "      x       x         x    ",
	  "      x   B   x    B    x    ",
	  "      x   B   x    B    x    ",
	  "      x   B   x    B    x    ",
	  "    o o o B o o o  B    x    ",
	  " B    o   o   B    B    B    ",
	  " B    o   o   o         o    ",
	  " B            B         B    ",
	  " B            o         o    ",
	  " B      1     B         B    ",
	  "!!xxxxxxxxxxxxxxxx!!!!!!x!!!!",
];

var bungeeJump = [
	  "                         x                                        ",
	  "                         v                                  o     ",
	  "                                                            o     ",
	  "                             x                              o     ",
	  "                xo    =      x                          x   o     ",
	  "                xxx   x  o   x                              o     ",
	  "                 |    x  o                    o             o     ",
	  "                    xxx  o                    o        o          ",
	  "                 |  x    o     x        =     o        x          ",
	  "                    x    o     x     =     =           x          ",
	  "  x                xx          x  =           =        x          ",
	  "  x         o o    x           o      o       o                   ",
	  "  x 1      xxxxx   x                        xxxxxx                ",
	  "  xxxxx            x     x     =                 x                ",
	  "      x!!!!!!!!!!!!x                             x                ",
	  "      xxxxxxxxxxxxxx       xx x xx xxx xxx       xxxxxxx    x     ",
	  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	];
	
var abyssRevisited = [
	  "                    x xx x       xxxx ",
	  "                    | xx v       v x  ",
	  "                      xx     1     x  ",
	  "                      xx     x     x  ",
	  "                      xx     x     x  ",
	  "           x=         xx    =x=    x  ",
	  "                    o x               ",
	  "                    xxx               ",
	  "                    x        o        ",
	  "     =              x        o        ",
	  "  x =              xx        o        ",
	  "  x         o o    x         x        ",
	  "  x        xxxxx   x                  ",
	  "  xxxxx            x     x       x    ",
	  "  xxxxx            |     x       x    ",
	  "  xxxxx  x               x   x   x  o ",
	  "  xxxxx    =             x       x  x ",
	  "  xxxxx   =              x       x    ",
	  "  xxxxx  =   o   o       o       x    ",
	  "  xxxxx      x   x       o   x   x    ",
	  "  xxxxx                  o   x   x    ",
	  "  xxxxx!!!!!!!!!!!!!!!xxxx!!!x!!!x!!!!",
	];

var gauntlet = [
	  "  =           o        o               | |     o           v     o              | |  ooo         v  v  v         o o o ",
	  " =                                                                      x     =x=|          x                    o o o ",
	  "=        1    o                o               o                 o      x                   x      o  o  o       o o o ",
	  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxx"
	  ];
var lavaWorld = [
	"                                                          ",
	"                                                          ",
	"                                                          ",
	"                                                          ",
	"       x      o                   o                       ",
	"       x      x         @       = x                       ",
	"       x      x =                 x                       ",
	"       x      x                   x                       ",
	"       x             x      x            x           x    ",
	"       x             |      |                        x    ",
	"       x      x                   x                  x    ",
	" x     x      |          1        |      o           xo  x",
	" |    ox               xxxxx             |           |   v",
	" o                                       xx          o   o",
	" o     |      o      |      |                o           o",
	" o     o      x   xxxx      xxxx  x          x       |   o",
	" x     |                                            xx   x",
	"       xx                                                 ",
	"                                                          ",
	"                                                          ",
	"                                                          ",
	"                                                          ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
];

var bunnyWorld = [
	  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	  "!                         o    o         !         o           ",
	  "!            o      o     o    o     o  o  o  o                ",
	  "!   1        !      !     !    !     x  xxxxxxxx        !  oooo",
	  "!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
];

	 
var bombAway = [
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"!       |       x  | | |  x      xxxxxx | xxx| |   |xx!!",
	"!               x         x| | | x   |x  |xx| |      o!!",
	"!               x         x      x    x   xx        xx!!",
	"!   1 #        oxo       ox     ox   ox  oxo        xo!!",
	"!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
];
var toTheSky =[
	"                    xx=  o    xx                 xx  =ox  ",
	"                    v    x     v            x     x  ox   ",
	"                         v                  x=    x ox    ",
	"       x                                          x x     ",
	"       x            x@oooooooo@x                          ",
	"       x            xxxxxxxxxxxx                          ",
	"       x                                      p           ",
	"       x                                      x           ",
	"       x                                                  ",
	"       x     xxx                 xxx                      ",
	"       x     xox=                xox        x             ",
	"       x     xxx                 xxx                      ",
	"       x     =x                   x                       ",
	"      ox      x          #        x      x                ",
	"      ox             x      x                             ",
	"      ox                                                  ",
	"       x                 1                                ",
	"       x  x      x       x     x                          ",
	"                                                          ",
	"=             x                                           ",
	"      x                                                   ",
	"                                                          ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
];	  
var intoTheMines = [
	"!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"     #      !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"     x      !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            xxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"=          1xo   xo  =xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"!!!!!!!!!!!xxo   xo=  xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxx | xxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxxo  xxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxxo  xxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxx!xxx!xx!xx!xx!xx!xo  xxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxx!xxx!xx!xx!xx!xx!xo  x     =oooxxxxxxxxxxxxxxxx",
	"xxx!xxx!xx!xx!xx!xx!xo  xxxxxxx   vxx|xxxxxxxxxxxx",
	"xxx!xxx!xx!xx!xx!xx!xo  xx!x!x!    xx |xxxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxx   xx!x!x!xp  xx  |xxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      |xxx xxxxx",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo   xxx xxxxx",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo  xxx xxxxx",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo   x|    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    =x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   = x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx =   x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  o  x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!x!!x"
];

var foolsGold = [
	  "xxxxxxxxxxxxxxxxxxxxxx",
	  "!oooooooooooooooz     ",
	  "!oooooooooxxxxxxzxx+xx",
	  "!ooooooooo!     z    !",
	  "!oooooxxxx!     z    !",
	  "!oooox!   z     z    !",
	  "!xxxxx!   z     zxxxxx",
	  "!x   z    z     z    !",
	  "!x   z    z     z  o !",
	  "!x1 #z    z     z    !",
	  "!xxxxxxxxxxxxxxxxxxxx!",
	  "!!!!!!!!!!!!!!!!!!!!!!",
	];

var chase = [
	  "2        o2        o 2",
	  "o        o         o  ",
	  "x        o         o  ",
	  "2    o   x    o    o  ",
	  "     o        o    x  ",
	  "     o        o       ",
	  "     x        x       ",
	  "                      ",
	  " 1        2o       o2 ",
	  "!xxxxxxxxxxxxxxxxxxxx!",
	  "!!!!!!!!!!!!!!!!!!!!!!",
];

var weepingAngel = [
	  "                                                                      x   ",
	  "                                                                    2  x  ",
	  "                                                                   o    x ",
	  "                                                                   xo |  x",
	  "                                                               o    xo |  ",
	  "                                                               x     xo | ",
	  "                                                           o          xo  ",
	  "                                                           x           xo ",
	  "  ooooooooooooooooooooooooooooooooooooooooooooooooooooo                 xo",
	  " 1oooooooooooooooooooooooooooooooooooooooooooooooooooo3                  x",
	  "!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!",
	  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
];
var iceWorld = [
	" @     o                           ",
	" xxxxxxxxxxxx    =    ox-      !  o",
	"            x-         x=         o",
	"            x!!!!!!!!!xx          o",
	"+                          xxxxxxxx",
	" o                                 ",
	"xx                                 ",
	"      x=          x                ",
	"                - x=               ",
	"                  xx    x      -x1 ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
];

var elevator = [
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"                       x     x      ",
	"                       x     !      ",
	"                       x            ",
	"                       x      -     ",
	"          +            !     !      ",
	"                          +  x      ",
	"                             x      ",
	"              +        p     x     !",
	"                       x     x     o",
	"     +                       x     o",
	"                 +           x     o",
	"+                            x     o",
	"                             x     o",
	"1                   +        x     o",
	"x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x"

];

var hell = [
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    1     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    o     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!  o       !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!o         !!!!!!!!!!!!!!!!!!!!!!!", 
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    o     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    o     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    o     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    o     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    o     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    o     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    o     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!    o     !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!          !!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!              = = = = = = =!!!!!!",
    "!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx  !!!!!!",
    "!!!!!!!!!!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!  !!!!!!",
    "xxxxxxxxxxxxxxxxxxxxxxxxx     v  v  o  v  o       !!",
    "xxxxxxxxxxxxxxxxxxxxxxxxx                         !!",
    "xxxxxxxxxxxxxxxxxxxxxxxxx     o  o  !  o  !       !!",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxx!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!",
    "!o      o      o                 o       o       o !",
    "!=      =      =      =                            !",
    "!                                                  !",
    "!                                                  !",
    "!                 -x         x-                    !",
    "!                                                  !",
    "!                                                  !",
    "!              x        x           x              !",
    "! =                                                !",
    "!                         =                        !",
    "!                       p                        = !",
    "! x      x              x                 x        !",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=====     @x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxx",
    "!oooooooooooooooooooooooooooooooooooooooo!!!!!!!!!!!",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
];


var MASTER_DICT = {
    "Unit Test World": [unitTest, {}, ""],
    "Easy": [easy, {}, "bach_gigue_english.mp3"],
    "Simple Abyss": [simpleAbyss, {}, "bach_gigue_english.mp3"],
    "Bungee Jump": [bungeeJump, {}, "bach_gigue_english.mp3"],
    "Lava World": [lavaWorld, {"=": 4}, "bach_gigue_french.mp3"],
    "Abyss Revisited": [abyssRevisited, {}, "bach_gigue_french.mp3"],
    "Chase": [chase, {}, "vivaldi_pianoguysfrozen.mp3"],
    "Gauntlet": [gauntlet, {"=": 3}, "schubert_erlkonig.mp3"],
    "Bomb Away": [bombAway, {"|": 2, "v": 2}, "bach_gigue_french.mp3"],
    "To the Sky": [toTheSky, {"=": 3}, "bach_gigue_english.mp3"],
    "Weeping Angel": [weepingAngel, {}, "bach_gigue_english.mp3"],
    "Ice World": [iceWorld, {"=": 4, "-": 3}, "vivaldi_pianoguysfrozen.mp3"],
    "Elevator": [elevator, {"+": 3, "-":3}, "vivaldi_pianoguysfrozen.mp3"],
    "Bunny World": [bunnyWorld, {}, "grieg_hallofthemountainking.mp3"],
    "Fool's Gold": [foolsGold, {}, "grieg_hallofthemountainking.mp3"], 
    "Into the Mines": [intoTheMines, {"=": 4}, "grieg_hallofthemountainking.mp3"],
    "Hell": [hell, {"=": 4, "-": 5}, "stravinsky_riteofspring.mp3"]
};
/*final ordering of levels*/
var ALL_NAMES = [ 
        "Easy", "Simple Abyss", "Bungee Jump", 
        "Lava World", "Abyss Revisited", "Chase", "Gauntlet",
        "Bomb Away",  "To the Sky", "Weeping Angel",
        "Ice World", "Elevator", 
        "Bunny World", "Fool's Gold", "Into the Mines",
        "Hell"  ];
        
var ALL_PLANS = [];
var ALL_SPEED_MULTIPLIERS = [];
var ALL_BACKGROUND_MUSICS = [];
var ALL_LEVEL_IDS = [];
for(var i = 0; i < ALL_NAMES.length; i++) {
    ALL_PLANS.push(MASTER_DICT[ALL_NAMES[i]][0]);
    ALL_SPEED_MULTIPLIERS.push(MASTER_DICT[ALL_NAMES[i]][1]);
    ALL_BACKGROUND_MUSICS.push(MASTER_DICT[ALL_NAMES[i]][2]);
    ALL_LEVEL_IDS.push(i + 1); //increment by one because of zero-based indexing
};

var ALL_LEVELS_CONFIG = {
    "plans": ALL_PLANS, 
    "names": ALL_NAMES, 
    "speed_multipliers": ALL_SPEED_MULTIPLIERS, 
    "background_musics": ALL_BACKGROUND_MUSICS, 
    "level_ids": ALL_LEVEL_IDS
}