var unitTest = [
	  "                                          ",
	  "                                          ",
	  "                                          ",
	  "                      xxxxxxx             ",
	  "                                          ",
	  "              xxxx                        ",
	  "                               xxxxx      ",
	  "                                          ",
	  "     =                 =xxx               ",
	  "                                          ",
	  "     x=    =      =   ! x                 ",
	  "                    x        2xxx         ",
	  "                                    o     ",
	  "                                    o     ",
	  "                                    oxx   ",
	  " 1       o   o    o                 ov|   ",
	  "xx        -x                            xx",
	  "!                   +                   v|",
	  "!  z   zp    p      x                     ",
	  "!  y   y#@         Bx                     ",
	  "!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	];
var introLevel = [
	  "                   x  ",
	  "             o     |  ",
	  "             o        ",
	  "             o        ",
	  "             x        ",
	  "                   o  ",
	  "  x=               x  ",
	  "  x         o o    x  ",
	  "  x        xxxxx   x  ",
	  "  x  1             x  ",
	  "  x!!xx!!!!!!!!!!!!x  ",
	  "      xxxxxxxxxxxxxx  ",
	  "                      "
	];
	
var simpleAbyss = [
	  "                    x xx x       xxxx ",
	  "                      xx v       v x  ",
	  "                      xx     x     x  ",
	  "                      xx v   x   v x  ",
	  "                      xx     x     x  ",
	  "                      xx     x     x  ",
	  "                      x      v        ",
	  "                    xxx               ",
	  "                   ox                 ",
	  "                   =x                 ",
	  "  x                xx        1        ",
	  "  x             o  x         x        ",
	  "  x   =         o  x                  ",
	  "  xxxxx         o  x     o       x    ",
	  "  xxxxx         x  x     o       x    ",
	  "  xxxxx  o      B        o   x   x    ",
	  "  xxxxx  x               o   x   x    ",
	  "  xxxxx                  o   x   x    ",
	  "  xxxxx       o          o   x   x    ",
	  "  xxxxx      xxxxx       o   x   x    ",
	  "  xxxxx                  o   x   x    ",
	  "  xxxxx!!!!!!!!!!!!!!!xxxx!!!x!!!x!!!!",
	];
	
var bombsGalore = [
	  "      x       x         x    ",
	  "      x   B   x    B    x    ",
	  "      x   B   x    B    x    ",
	  "      x   B   x    B    x    ",
	  "    o o o B o o o  B    x    ",
	  " B    o   o   B    B    B    ",
	  " B    o   o   o         o    ",
	  " B            B         B    ",
	  " B            o         o    ",
	  " B      1     B         B    ",
	  "!!xxxxxxxxxxxxxxxx!!!!!!x!!!!",
];

var bungeeJump = [
	  "                         x                    x                   ",
	  "                         v                                  o     ",
	  "                                                            o     ",
	  "                             x                         x    o     ",
	  "                xo    =      x                              o     ",
	  "                xxx   x  o   x                      x       o     ",
	  "                 |    x  o                                  o     ",
	  "                    xxx  o                    x        o          ",
	  "                 |  x    o     x        =     o        x          ",
	  "                    x    o     x      =       =        x          ",
	  "  x                xx          x  =      =    =        x          ",
	  "  x         o o    x           o                                  ",
	  "  x 1      xxxxx   x                        xxxxxx                ",
	  "  xxxxx            x     x     =                 x                ",
	  "      x!!!!!!!!!!!!x                             x                ",
	  "      xxxxxxxxxxxxxx       xx x xx xxx xxx       xxxxxxx          ",
	  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	];
	
var abyssRevisited = [
	  "                    x xx x       xxxx ",
	  "                    | xx v       v x  ",
	  "                      xx     1     x  ",
	  "                      xx     x     x  ",
	  "                      xx     x     x  ",
	  "           x=         xx    =x=    x  ",
	  "                    o x               ",
	  "                    xxx               ",
	  "                    x        o        ",
	  "     =              x        o        ",
	  "  x =              xx        o        ",
	  "  x         o o    x         x        ",
	  "  x        xxxxx   x                  ",
	  "  xxxxx            x     x       x    ",
	  "  xxxxx            |     x       x    ",
	  "  xxxxx  x               x   x   x  o ",
	  "  xxxxx    =             x       x  x ",
	  "  xxxxx   =              x       x    ",
	  "  xxxxx  =   o   o       o       x    ",
	  "  xxxxx      x   x       o   x   x    ",
	  "  xxxxx                  o   x   x    ",
	  "  xxxxx!!!!!!!!!!!!!!!xxxx!!!x!!!x!!!!",
	];

var gauntlet = [
	  "  =           o        o               | |     o           v     o              | |  ooo         v  v  v         o o o ",
	  " =                                                                      x     =x=|          x                    o o o ",
	  "=        1    o                o               o                 o      x                   x      o  o  o       o o o ",
	  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxx"
	  ];
var lavaWorld = [
	"                                                          ",
	"                                                          ",
	"                                                          ",
	"                                                          ",
	"       x      o                   o                       ",
	"       x      x         @       = x                       ",
	"       x      x =                 x                       ",
	"       x      x                   x                       ",
	"       x             x      x            x           x    ",
	"       x             |      |                        x    ",
	"       x      x                   x                  x    ",
	" x     x      |          1        |      o           xo  x",
	" |    ox               xxxxx             |           |   v",
	" o                                       xx          o   o",
	" o     |      o      |      |                o           o",
	" o     o      x   xxxx      xxxx  x          x       |   o",
	" x     |                                            xx   x",
	"       xx                                                 ",
	"                                                          ",
	"                                                          ",
	"                                                          ",
	"                                                          ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
];

var bunnyWorld = [
	  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	  "!                         o    o         !         o           ",
	  "!            o      o     o    o     o  o  o  o                ",
	  "!   1        !      !     !    !     x  xxxxxxxx        !  oooo",
	  "!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
];

	 
var bombAway = [
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"!       |       x  | | |  x      xxxxxx | xxx| |   |xx!!",
	"!               x         x| | | x   |x  |xx| |      o!!",
	"!               x         x      x    x   xx        xx!!",
	"!   1 #        oxo       ox     ox   ox  oxo        xo!!",
	"!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
];
var toTheSky =[
	"                    xx=  o    xx                 xx  =ox  ",
	"                    v    x     v            x     x  ox   ",
	"                         v                  x=    x ox    ",
	"       x                                          x x     ",
	"       x            x@oooooooo@x                          ",
	"       x            xxxxxxxxxxxx                          ",
	"       x                                      p           ",
	"       x                                      x           ",
	"       x                                                  ",
	"       x     xxx                 xxx                      ",
	"       x     xox=                xox        x             ",
	"       x     xxx                 xxx                      ",
	"       x     =x                   x                       ",
	"      ox      x          #        x      x                ",
	"      ox             x      x                             ",
	"      ox                                                  ",
	"       x                 1                                ",
	"       x  x      x       x     x                          ",
	"                                                          ",
	"=             x                                           ",
	"      x                                                   ",
	"                                                          ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
];	  
var intoTheMines = [
	"!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"     #      !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"     x      !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            !xx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"            xxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"=          1xo   xo   xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"!!!!!!!!!!!xxo   xo=  xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxx | xxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxxo  xxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxxo  xxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxx!xxx!xx!xx!xx!xx!xo  xxxxxxxxxxxxxxxxxxxxxxxxxx",
	"xxx!xxx!xx!xx!xx!xx!xo  x     =oooxxxxxxxxxxxxxxxx",
	"xxx!xxx!xx!xx!xx!xx!xo  xxxxxxx   vxx|xxxxxxxxxxxx",
	"xxx!xxx!xx!xx!xx!xx!xo  xx!x!x!    xx |xxxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxx   xx!x!x!xp  xx  |xxxxxxxxxx",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      |xxx xxxxx",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo   xox xxxxx",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo  xox xxxxx",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo   y|    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    =x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   = x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx =   x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=    x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  o  x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!x!!x"
];

var foolsGold = [
	  "xxxxxxxxxxxxxxxxxxxxxx",
	  "!oooooooooooooooz     ",
	  "!oooooooooxxxxxxzxx+xx",
	  "!ooooooooo!     z    !",
	  "!oooooxxxx!     z    !",
	  "!oooox!   z     z    !",
	  "!xxxxx!   z     zxxxxx",
	  "!x   z    z     z    !",
	  "!x   z    z     z  o !",
	  "!x1 #z    z     z    !",
	  "!xxxxxxxxxxxxxxxxxxxx!",
	  "!!!!!!!!!!!!!!!!!!!!!!",
	];

var chase = [
	  "2                  o 2",
	  "o                     ",
	  "x        o            ",
	  "         x         o  ",
	  "                   x  ",
	  "     o        o       ",
	  "     x        x       ",
	  "                      ",
	  " 1         o       o2 ",
	  "!xxxxxxxxxxxxxxxxxxxx!",
	  "!!!!!!!!!!!!!!!!!!!!!!",
];
var iceWorld = [
	" @     o                           ",
	" xxxxxxxxxxxx    =    ox-      !  o",
	"            x-         x=         o",
	"            x!!!!!!!!!xx          o",
	"+                          xxxxxxxx",
	" o                                 ",
	"xx                                 ",
	"      x=          x                ",
	"                - x=               ",
	"                  xx    x      -x1 ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx",
];

var elevator = [
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"                       x     x      ",
	"                       x     !      ",
	"                       x            ",
	"                       x      -     ",
	"          +            !     !      ",
	"                          +  x      ",
	"                             x      ",
	"              +        p     x     !",
	"                       x     x     o",
	"     +                       x     o",
	"                 +           x     o",
	"+                            x     o",
	"                             x     o",
	"1                   +        x     o",
	"x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x"

];

var ALL_LEVELS = [unitTest, introLevel, simpleAbyss, bungeeJump, abyssRevisited, gauntlet,
		bunnyWorld, lavaWorld, bombAway, toTheSky, foolsGold, chase, iceWorld, elevator, intoTheMines];

var ALL_SPEED_MULTIPLIERS = [{}, {}, {}, {}, {}, {"=": 3}, 
		{}, {"=": 4}, {"|": 2, "v": 2}, {"=": 3}, {}, {}, {"=": 4, "-": 3}, {"+": 3, "-":3}, {"=": 4}];

var ALL_NAMES = ["Unit Test World", "Intro", "Simple Abyss", "Bungee Jump", "Abyss Revisted", 
				"Gauntlet", "Bunny World", "Lava World", "Bomb Away", "To the Sky", "Fool's Gold", "Chase", 
				"Ice World", "Elevator", "Into the Mines"];
